# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-08 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(db_column='Customer Id', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='Email', max_length=45, unique=True)),
                ('first_name', models.CharField(db_column='First Name', max_length=45)),
                ('last_name', models.CharField(db_column='Last Name', max_length=45)),
                ('phone_number', models.CharField(db_column='Phone Number', max_length=45, unique=True)),
                ('address', models.CharField(db_column='Address', max_length=45)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
    ]
