# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-08 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(db_column='Employee Id', primary_key=True, serialize=False)),
                ('role', models.CharField(db_column='Role', max_length=45)),
                ('data_joined', models.DateTimeField(db_column='Data Joined')),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
    ]
