# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('item_id', models.ForeignKey(db_column='Item Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='shop.Inventory')),
                ('seller', models.CharField(blank=True, db_column='Seller', max_length=45, null=True)),
                ('ratings', models.IntegerField(db_column='Ratings')),
                ('detailed_review', models.TextField(blank=True, db_column='Detailed Review', null=True)),
            ],
            options={
                'db_table': 'Review',
                'managed': False,
            },
        ),
    ]
