# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-08 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.IntegerField(db_column='Item Id', primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_column='Item Name', max_length=45)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('price', models.IntegerField(db_column='Price')),
                ('seller', models.CharField(db_column='Seller', max_length=45)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Inventory',
                'managed': False,
            },
        ),
    ]
